"""ISO 3166-1 alpha-2 country list for KYC master data fallbacks."""

from __future__ import annotations

_STATIC_KYC_COUNTRIES: list[dict[str, str]] = [
    {"name": "India", "ansi_code": "IN"},
    {"name": "Afghanistan", "ansi_code": "AF"},
    {"name": "Albania", "ansi_code": "AL"},
    {"name": "Algeria", "ansi_code": "DZ"},
    {"name": "American Samoa", "ansi_code": "AS"},
    {"name": "Andorra", "ansi_code": "AD"},
    {"name": "Angola", "ansi_code": "AO"},
    {"name": "Anguilla", "ansi_code": "AI"},
    {"name": "Antarctica", "ansi_code": "AQ"},
    {"name": "Antigua and Barbuda", "ansi_code": "AG"},
    {"name": "Argentina", "ansi_code": "AR"},
    {"name": "Armenia", "ansi_code": "AM"},
    {"name": "Aruba", "ansi_code": "AW"},
    {"name": "Australia", "ansi_code": "AU"},
    {"name": "Austria", "ansi_code": "AT"},
    {"name": "Azerbaijan", "ansi_code": "AZ"},
    {"name": "Bahamas", "ansi_code": "BS"},
    {"name": "Bahrain", "ansi_code": "BH"},
    {"name": "Bangladesh", "ansi_code": "BD"},
    {"name": "Barbados", "ansi_code": "BB"},
    {"name": "Belarus", "ansi_code": "BY"},
    {"name": "Belgium", "ansi_code": "BE"},
    {"name": "Belize", "ansi_code": "BZ"},
    {"name": "Benin", "ansi_code": "BJ"},
    {"name": "Bermuda", "ansi_code": "BM"},
    {"name": "Bhutan", "ansi_code": "BT"},
    {"name": "Bolivia, Plurinational State of", "ansi_code": "BO"},
    {"name": "Bonaire, Sint Eustatius and Saba", "ansi_code": "BQ"},
    {"name": "Bosnia and Herzegovina", "ansi_code": "BA"},
    {"name": "Botswana", "ansi_code": "BW"},
    {"name": "Bouvet Island", "ansi_code": "BV"},
    {"name": "Brazil", "ansi_code": "BR"},
    {"name": "British Indian Ocean Territory", "ansi_code": "IO"},
    {"name": "Brunei Darussalam", "ansi_code": "BN"},
    {"name": "Bulgaria", "ansi_code": "BG"},
    {"name": "Burkina Faso", "ansi_code": "BF"},
    {"name": "Burundi", "ansi_code": "BI"},
    {"name": "Cabo Verde", "ansi_code": "CV"},
    {"name": "Cambodia", "ansi_code": "KH"},
    {"name": "Cameroon", "ansi_code": "CM"},
    {"name": "Canada", "ansi_code": "CA"},
    {"name": "Cayman Islands", "ansi_code": "KY"},
    {"name": "Central African Republic", "ansi_code": "CF"},
    {"name": "Chad", "ansi_code": "TD"},
    {"name": "Chile", "ansi_code": "CL"},
    {"name": "China", "ansi_code": "CN"},
    {"name": "Christmas Island", "ansi_code": "CX"},
    {"name": "Cocos (Keeling) Islands", "ansi_code": "CC"},
    {"name": "Colombia", "ansi_code": "CO"},
    {"name": "Comoros", "ansi_code": "KM"},
    {"name": "Congo", "ansi_code": "CG"},
    {"name": "Congo, The Democratic Republic of the", "ansi_code": "CD"},
    {"name": "Cook Islands", "ansi_code": "CK"},
    {"name": "Costa Rica", "ansi_code": "CR"},
    {"name": "Croatia", "ansi_code": "HR"},
    {"name": "Cuba", "ansi_code": "CU"},
    {"name": "Curaçao", "ansi_code": "CW"},
    {"name": "Cyprus", "ansi_code": "CY"},
    {"name": "Czechia", "ansi_code": "CZ"},
    {"name": "Côte d'Ivoire", "ansi_code": "CI"},
    {"name": "Denmark", "ansi_code": "DK"},
    {"name": "Djibouti", "ansi_code": "DJ"},
    {"name": "Dominica", "ansi_code": "DM"},
    {"name": "Dominican Republic", "ansi_code": "DO"},
    {"name": "Ecuador", "ansi_code": "EC"},
    {"name": "Egypt", "ansi_code": "EG"},
    {"name": "El Salvador", "ansi_code": "SV"},
    {"name": "Equatorial Guinea", "ansi_code": "GQ"},
    {"name": "Eritrea", "ansi_code": "ER"},
    {"name": "Estonia", "ansi_code": "EE"},
    {"name": "Eswatini", "ansi_code": "SZ"},
    {"name": "Ethiopia", "ansi_code": "ET"},
    {"name": "Falkland Islands (Malvinas)", "ansi_code": "FK"},
    {"name": "Faroe Islands", "ansi_code": "FO"},
    {"name": "Fiji", "ansi_code": "FJ"},
    {"name": "Finland", "ansi_code": "FI"},
    {"name": "France", "ansi_code": "FR"},
    {"name": "French Guiana", "ansi_code": "GF"},
    {"name": "French Polynesia", "ansi_code": "PF"},
    {"name": "French Southern Territories", "ansi_code": "TF"},
    {"name": "Gabon", "ansi_code": "GA"},
    {"name": "Gambia", "ansi_code": "GM"},
    {"name": "Georgia", "ansi_code": "GE"},
    {"name": "Germany", "ansi_code": "DE"},
    {"name": "Ghana", "ansi_code": "GH"},
    {"name": "Gibraltar", "ansi_code": "GI"},
    {"name": "Greece", "ansi_code": "GR"},
    {"name": "Greenland", "ansi_code": "GL"},
    {"name": "Grenada", "ansi_code": "GD"},
    {"name": "Guadeloupe", "ansi_code": "GP"},
    {"name": "Guam", "ansi_code": "GU"},
    {"name": "Guatemala", "ansi_code": "GT"},
    {"name": "Guernsey", "ansi_code": "GG"},
    {"name": "Guinea", "ansi_code": "GN"},
    {"name": "Guinea-Bissau", "ansi_code": "GW"},
    {"name": "Guyana", "ansi_code": "GY"},
    {"name": "Haiti", "ansi_code": "HT"},
    {"name": "Heard Island and McDonald Islands", "ansi_code": "HM"},
    {"name": "Holy See (Vatican City State)", "ansi_code": "VA"},
    {"name": "Honduras", "ansi_code": "HN"},
    {"name": "Hong Kong", "ansi_code": "HK"},
    {"name": "Hungary", "ansi_code": "HU"},
    {"name": "Iceland", "ansi_code": "IS"},
    {"name": "Indonesia", "ansi_code": "ID"},
    {"name": "Iran, Islamic Republic of", "ansi_code": "IR"},
    {"name": "Iraq", "ansi_code": "IQ"},
    {"name": "Ireland", "ansi_code": "IE"},
    {"name": "Isle of Man", "ansi_code": "IM"},
    {"name": "Israel", "ansi_code": "IL"},
    {"name": "Italy", "ansi_code": "IT"},
    {"name": "Jamaica", "ansi_code": "JM"},
    {"name": "Japan", "ansi_code": "JP"},
    {"name": "Jersey", "ansi_code": "JE"},
    {"name": "Jordan", "ansi_code": "JO"},
    {"name": "Kazakhstan", "ansi_code": "KZ"},
    {"name": "Kenya", "ansi_code": "KE"},
    {"name": "Kiribati", "ansi_code": "KI"},
    {"name": "Korea, Democratic People's Republic of", "ansi_code": "KP"},
    {"name": "Korea, Republic of", "ansi_code": "KR"},
    {"name": "Kuwait", "ansi_code": "KW"},
    {"name": "Kyrgyzstan", "ansi_code": "KG"},
    {"name": "Lao People's Democratic Republic", "ansi_code": "LA"},
    {"name": "Latvia", "ansi_code": "LV"},
    {"name": "Lebanon", "ansi_code": "LB"},
    {"name": "Lesotho", "ansi_code": "LS"},
    {"name": "Liberia", "ansi_code": "LR"},
    {"name": "Libya", "ansi_code": "LY"},
    {"name": "Liechtenstein", "ansi_code": "LI"},
    {"name": "Lithuania", "ansi_code": "LT"},
    {"name": "Luxembourg", "ansi_code": "LU"},
    {"name": "Macao", "ansi_code": "MO"},
    {"name": "Madagascar", "ansi_code": "MG"},
    {"name": "Malawi", "ansi_code": "MW"},
    {"name": "Malaysia", "ansi_code": "MY"},
    {"name": "Maldives", "ansi_code": "MV"},
    {"name": "Mali", "ansi_code": "ML"},
    {"name": "Malta", "ansi_code": "MT"},
    {"name": "Marshall Islands", "ansi_code": "MH"},
    {"name": "Martinique", "ansi_code": "MQ"},
    {"name": "Mauritania", "ansi_code": "MR"},
    {"name": "Mauritius", "ansi_code": "MU"},
    {"name": "Mayotte", "ansi_code": "YT"},
    {"name": "Mexico", "ansi_code": "MX"},
    {"name": "Micronesia, Federated States of", "ansi_code": "FM"},
    {"name": "Moldova, Republic of", "ansi_code": "MD"},
    {"name": "Monaco", "ansi_code": "MC"},
    {"name": "Mongolia", "ansi_code": "MN"},
    {"name": "Montenegro", "ansi_code": "ME"},
    {"name": "Montserrat", "ansi_code": "MS"},
    {"name": "Morocco", "ansi_code": "MA"},
    {"name": "Mozambique", "ansi_code": "MZ"},
    {"name": "Myanmar", "ansi_code": "MM"},
    {"name": "Namibia", "ansi_code": "NA"},
    {"name": "Nauru", "ansi_code": "NR"},
    {"name": "Nepal", "ansi_code": "NP"},
    {"name": "Netherlands", "ansi_code": "NL"},
    {"name": "New Caledonia", "ansi_code": "NC"},
    {"name": "New Zealand", "ansi_code": "NZ"},
    {"name": "Nicaragua", "ansi_code": "NI"},
    {"name": "Niger", "ansi_code": "NE"},
    {"name": "Nigeria", "ansi_code": "NG"},
    {"name": "Niue", "ansi_code": "NU"},
    {"name": "Norfolk Island", "ansi_code": "NF"},
    {"name": "North Macedonia", "ansi_code": "MK"},
    {"name": "Northern Mariana Islands", "ansi_code": "MP"},
    {"name": "Norway", "ansi_code": "NO"},
    {"name": "Oman", "ansi_code": "OM"},
    {"name": "Pakistan", "ansi_code": "PK"},
    {"name": "Palau", "ansi_code": "PW"},
    {"name": "Palestine, State of", "ansi_code": "PS"},
    {"name": "Panama", "ansi_code": "PA"},
    {"name": "Papua New Guinea", "ansi_code": "PG"},
    {"name": "Paraguay", "ansi_code": "PY"},
    {"name": "Peru", "ansi_code": "PE"},
    {"name": "Philippines", "ansi_code": "PH"},
    {"name": "Pitcairn", "ansi_code": "PN"},
    {"name": "Poland", "ansi_code": "PL"},
    {"name": "Portugal", "ansi_code": "PT"},
    {"name": "Puerto Rico", "ansi_code": "PR"},
    {"name": "Qatar", "ansi_code": "QA"},
    {"name": "Romania", "ansi_code": "RO"},
    {"name": "Russian Federation", "ansi_code": "RU"},
    {"name": "Rwanda", "ansi_code": "RW"},
    {"name": "Réunion", "ansi_code": "RE"},
    {"name": "Saint Barthélemy", "ansi_code": "BL"},
    {"name": "Saint Helena, Ascension and Tristan da Cunha", "ansi_code": "SH"},
    {"name": "Saint Kitts and Nevis", "ansi_code": "KN"},
    {"name": "Saint Lucia", "ansi_code": "LC"},
    {"name": "Saint Martin (French part)", "ansi_code": "MF"},
    {"name": "Saint Pierre and Miquelon", "ansi_code": "PM"},
    {"name": "Saint Vincent and the Grenadines", "ansi_code": "VC"},
    {"name": "Samoa", "ansi_code": "WS"},
    {"name": "San Marino", "ansi_code": "SM"},
    {"name": "Sao Tome and Principe", "ansi_code": "ST"},
    {"name": "Saudi Arabia", "ansi_code": "SA"},
    {"name": "Senegal", "ansi_code": "SN"},
    {"name": "Serbia", "ansi_code": "RS"},
    {"name": "Seychelles", "ansi_code": "SC"},
    {"name": "Sierra Leone", "ansi_code": "SL"},
    {"name": "Singapore", "ansi_code": "SG"},
    {"name": "Sint Maarten (Dutch part)", "ansi_code": "SX"},
    {"name": "Slovakia", "ansi_code": "SK"},
    {"name": "Slovenia", "ansi_code": "SI"},
    {"name": "Solomon Islands", "ansi_code": "SB"},
    {"name": "Somalia", "ansi_code": "SO"},
    {"name": "South Africa", "ansi_code": "ZA"},
    {"name": "South Georgia and the South Sandwich Islands", "ansi_code": "GS"},
    {"name": "South Sudan", "ansi_code": "SS"},
    {"name": "Spain", "ansi_code": "ES"},
    {"name": "Sri Lanka", "ansi_code": "LK"},
    {"name": "Sudan", "ansi_code": "SD"},
    {"name": "Suriname", "ansi_code": "SR"},
    {"name": "Svalbard and Jan Mayen", "ansi_code": "SJ"},
    {"name": "Sweden", "ansi_code": "SE"},
    {"name": "Switzerland", "ansi_code": "CH"},
    {"name": "Syrian Arab Republic", "ansi_code": "SY"},
    {"name": "Taiwan, Province of China", "ansi_code": "TW"},
    {"name": "Tajikistan", "ansi_code": "TJ"},
    {"name": "Tanzania, United Republic of", "ansi_code": "TZ"},
    {"name": "Thailand", "ansi_code": "TH"},
    {"name": "Timor-Leste", "ansi_code": "TL"},
    {"name": "Togo", "ansi_code": "TG"},
    {"name": "Tokelau", "ansi_code": "TK"},
    {"name": "Tonga", "ansi_code": "TO"},
    {"name": "Trinidad and Tobago", "ansi_code": "TT"},
    {"name": "Tunisia", "ansi_code": "TN"},
    {"name": "Turkmenistan", "ansi_code": "TM"},
    {"name": "Turks and Caicos Islands", "ansi_code": "TC"},
    {"name": "Tuvalu", "ansi_code": "TV"},
    {"name": "Türkiye", "ansi_code": "TR"},
    {"name": "Uganda", "ansi_code": "UG"},
    {"name": "Ukraine", "ansi_code": "UA"},
    {"name": "United Arab Emirates", "ansi_code": "AE"},
    {"name": "United Kingdom", "ansi_code": "GB"},
    {"name": "United States", "ansi_code": "US"},
    {"name": "United States Minor Outlying Islands", "ansi_code": "UM"},
    {"name": "Uruguay", "ansi_code": "UY"},
    {"name": "Uzbekistan", "ansi_code": "UZ"},
    {"name": "Vanuatu", "ansi_code": "VU"},
    {"name": "Venezuela, Bolivarian Republic of", "ansi_code": "VE"},
    {"name": "Viet Nam", "ansi_code": "VN"},
    {"name": "Virgin Islands, British", "ansi_code": "VG"},
    {"name": "Virgin Islands, U.S.", "ansi_code": "VI"},
    {"name": "Wallis and Futuna", "ansi_code": "WF"},
    {"name": "Western Sahara", "ansi_code": "EH"},
    {"name": "Yemen", "ansi_code": "YE"},
    {"name": "Zambia", "ansi_code": "ZM"},
    {"name": "Zimbabwe", "ansi_code": "ZW"},
    {"name": "Åland Islands", "ansi_code": "AX"},
]


def static_kyc_countries() -> list[dict[str, str]]:
    return [dict(item) for item in _STATIC_KYC_COUNTRIES]
