import type { DistributorInvestor } from "@/lib/distributor-types";

export const SUPPORT_DUMMY_INVESTORS: DistributorInvestor[] = [
  {
    id: "usr-001",
    displayName: "Ananya Sharma",
    emailMasked: "an***@gmail.com",
    panMasked: "ABCP****F",
    clientCode: "ZYND-U-001",
    mobileMasked: "98****2101",
    onboardingStatus: "Onboarded",
    complianceStatus: "Compliant",
    investmentStatus: "Invested",
    investorType: "Resident Individual",
    aum: 842_500,
    createdAt: "2025-06-12T08:00:00Z",
    inDistributorBook: true,
    serviceModel: "diy",
  },
  {
    id: "usr-002",
    displayName: "Rahul Mehta",
    emailMasked: "rah***@outlook.com",
    panMasked: "XYZP****K",
    clientCode: "ZYND-U-002",
    mobileMasked: "91****8832",
    onboardingStatus: "Onboarded",
    complianceStatus: "Non Compliant",
    investmentStatus: "Non Invested",
    investorType: "Resident Individual",
    aum: null,
    createdAt: "2025-09-03T10:15:00Z",
    inDistributorBook: true,
    serviceModel: "pm",
  },
  {
    id: "usr-003",
    displayName: "Priya Nair",
    emailMasked: "pri***@yahoo.com",
    panMasked: "PQRS****L",
    clientCode: "ZYND-U-003",
    mobileMasked: "99****4410",
    onboardingStatus: "Pending",
    complianceStatus: "Non Compliant",
    investmentStatus: "Non Invested",
    investorType: "Resident Individual",
    aum: null,
    createdAt: "2026-01-20T14:30:00Z",
    inDistributorBook: true,
    serviceModel: "diy",
  },
  {
    id: "usr-004",
    displayName: "Vikram Singh",
    emailMasked: "vik***@icloud.com",
    panMasked: "LMNO****T",
    clientCode: "ZYND-U-004",
    mobileMasked: "97****9921",
    onboardingStatus: "Onboarded",
    complianceStatus: "Compliant",
    investmentStatus: "Invested",
    investorType: "Resident Individual",
    aum: 1_245_000,
    createdAt: "2024-11-02T09:00:00Z",
    inDistributorBook: true,
    serviceModel: "diy",
  },
  {
    id: "usr-005",
    displayName: "Sneha Patel",
    emailMasked: "sne***@gmail.com",
    panMasked: "DEFG****H",
    clientCode: "ZYND-U-005",
    mobileMasked: "96****7712",
    onboardingStatus: "Onboarded",
    complianceStatus: "Compliant",
    investmentStatus: "Invested",
    investorType: "Resident Individual",
    aum: 325_800,
    createdAt: "2025-03-18T11:45:00Z",
    inDistributorBook: true,
    serviceModel: "pm",
  },
];
